// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'tartalomjegyzek',
      label: 'Tartalomjegyzék',
    },
    {
      type: 'category',
      label: 'Kezdő lépések és fiókkezelés',
      link: {
        type: 'generated-index',
        description: 'Minden, ami az identiGO használatának megkezdéséhez és a fiók kezeléséhez szükséges.',
      },
      items: [
        {type: 'autogenerated', dirName: '1. Regisztráció és hozzáférés'},
        {type: 'autogenerated', dirName: '2. Hogyan tudok regisztrálni az identiGO-ba'},
        {type: 'autogenerated', dirName: '3. Ajánlói program'},
        {type: 'autogenerated', dirName: '4. Előfizetés & számlázás'},
      ],
    },
    {
      type: 'category',
      label: 'Szervezeti beállítások',
      link: {
        type: 'generated-index',
        description: 'Szolgáltatók és csoportok kezelése a hatékonyabb munkaszervezésért.',
      },
      items: [
        {type: 'autogenerated', dirName: '5. Szolgáltatók kezelése (multi-company használat)'},
        {type: 'autogenerated', dirName: '6. Cégcsoportok & Ügyfélcsoportok'},
      ],
    },
    {
      type: 'category',
      label: 'Ügyfélkezelés és munkafolyamatok',
      link: {
        type: 'generated-index',
        description: 'Ügyfelek felvitele, adatlapok kezelése és automatikus adatkitöltés.',
      },
      items: [
        {type: 'autogenerated', dirName: '7. Ügyfelek hozzáadása — teljes folyamat'},
        {type: 'autogenerated', dirName: '8. Automatikus adatkitöltés'},
        {type: 'autogenerated', dirName: '9. Ügyfél adatlap részei'},
        {type: 'autogenerated', dirName: '10. Képviselők, tulajdonosok, tényleges tulajdonosok'},
        {type: 'autogenerated', dirName: '19. Tömeges műveletek és ügyfelek szűrése'},
      ],
    },
    {
      type: 'category',
      label: 'Átvilágítás és Megfelelőség',
      link: {
        type: 'generated-index',
        description: 'AML/CFT megfelelőség, kockázati besorolás és dokumentumkezelés.',
      },
      items: [
        {type: 'autogenerated', dirName: '11. Dokumentumfeltöltés & dokumentumkezelés'},
        {type: 'autogenerated', dirName: '12. Kockázati besorolás & monitoring'},
        {type: 'autogenerated', dirName: '13. Ügyfélátvilágítási adatlap'},
        {type: 'autogenerated', dirName: '14. TTNY (Tényleges tulajdonosi nyilvántartás)'},
        {type: 'autogenerated', dirName: '15. Szűrések és listák — teljes áttekintés'},
        {type: 'autogenerated', dirName: '21. Tényleges Tulajdonos modul'},
      ],
    },
    {
      type: 'category',
      label: 'Extra funkciók és Biztonság',
      link: {
        type: 'generated-index',
        description: 'Cégfigyelés, adatszinkronizáció, exportok és biztonsági kérdések.',
      },
      items: [
        {type: 'autogenerated', dirName: '16. Cégfigyelés & értesítések'},
        {type: 'autogenerated', dirName: '17. Változástörténet & Céginfo'},
        {type: 'autogenerated', dirName: '18. Adatszinkron (Opten ↔ identiGO)'},
        {type: 'autogenerated', dirName: '20. Exportok'},
        {type: 'autogenerated', dirName: '22. Informatikai, biztonsági és adattárolási kérdések'},
      ],
    },
  ],
};

export default sidebars;
